name: Continuous Integration
on: [push, pull_request]
env:
  RUNNER: ubuntu-latest
  JAVA_VERSION: 1.8

jobs:
  build:
    name: Build
    runs-on: $RUNNER
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: $JAVA_VERSION
      - name: Build
        run: mvn -B clean package

  verify:
    name: Verify
    needs: build
    runs-on: $RUNNER
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up environment
        uses: actions/setup-java@v1
        with:
          java-version: $JAVA_VERSION
      - name: Verify
        run: mvn verify sonar:sonar        
